version: "3.7"

services:
  blind-ca:
    image: ghcr.io/vocdoni/blind-ca:${BLINDCA_TAG:-latest}
    sysctls:
      net.core.somaxconn: 8128
    env_file:
      - .env
    volumes:
      - blind-ca:/app/data
    ports:
      - 443:5000
    restart: unless-stopped
volumes:
  blind-ca: {}
